server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.135:8848
  elasticsearch:
    rest:
      uris: http://192.168.17.135:9200
  rabbitmq:
    host: 192.168.17.135
    virtual-host: /lzc
    username: lzc
    password: 782954