server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.135:8848
  datasource:
    url: jdbc:mysql://192.168.17.135:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 782954
  redis:
    host: 192.168.17.135
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/ums/**/*.xml